board:

  battleground16x16:
    shape: [ 16, 16 ]
    default: OPEN_GROUND

    terrain:
      CONCRETE_BUILDING:
        - line: [ 6, 3, 6, 5 ]
        - line: [ 8, 12, 12, 10 ]
        - line: [ 9, 13, 14, 10 ]
        - line: [ 10, 13, 14, 11 ]
        - line: [ 11, 14, 15, 12 ]
        - line: [ 11, 15, 13, 14 ]
        - point: [ 9, 4 ]
        - point: [ 9, 5 ]
        - point: [ 10, 4 ]
        - point: [ 4, 9 ]
        - point: [ 3, 9 ]
        - point: [ 3, 10 ]

      TREE:
        - point: [ 6, 9 ]
        - point: [ 7, 8 ]
        - point: [ 11, 5 ]
        - point: [ 10, 11 ]

      FOREST:
        - line: [ 2, 6, 4, 5 ]
        - line: [ 2, 7, 4, 6 ]
        - line: [ 9, 0, 15, 0 ]
        - line: [ 12, 1, 15, 1 ]
        - line: [ 13, 2, 14, 2 ]

      ROAD:
        - line: [ 0, 1, 5, 4 ]
        - line: [ 5, 4, 5, 8 ]
        - line: [ 0, 8, 5, 8 ]
        - line: [ 5, 8, 15, 13 ]
        - line: [ 10, 7, 15, 5 ]
        - line: [ 10, 7, 10, 10 ]
        - line: [ 2, 12, 8, 9 ]
        - line: [ 2, 12, 2, 15 ]
