version: '3.3'

services:

  ntw:
    image: ntw-backend:latest
    build:
      context: ./code
      dockerfile: Dockerfile
    container_name: ntw_web_backend

  front:
    image: ntw-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ntw_web_frontend
    links:
      - "ntw:backend"
