services:

  ntw:
    image: ntw-backend:latest
    build:
      context: ./code
      dockerfile: Dockerfile
    container_name: ntw_web_backend

  front:
    image: ntw-frontend:latest
    build:
      context: ./frontend
      docekrfile: Dockerfile
    container_name: ntw_web_frontend
    environment: 
      API_URL: "ntw_web_backend:5000/"
