version: 1
formatters:
  standard:
    datefmt: '%Y-%m-%d %H:%M:%S'
    format: '%(asctime)s %(levelname)s %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    formatter: standard
    stream: ext://sys.stdout

  agents_file_handler:
    class: logging.FileHandler
    formatter: standard
    filename: logs/agents.info.log
    encoding: utf8

  agents_file_warning_handler:
    class: logging.FileHandler
    formatter: standard
    filename: logs/agents.warn.log
    encoding: utf8

  web_file_handler:
    class: logging.FileHandler
    formatter: standard
    filename: logs/web.log
    encoding: utf8

  tourney_file_handler:
    class: logging.FileHandler
    formatter: standard
    filename: logs/tourney.all.log
    encoding: utf8

root:
  level: NOTSET
  handlers: [ console ]
  propagate: yes

loggers:
  agents:
    level: INFO
    handlers: [ agents_file_handler ]
    propagate: no

  agents.ml:
    level: WARNING
    handlers: [ agents_file_warning_handler ]
    propagate: yes

  web:
    level: INFO
    handlers: [ web_file_handler ]
    propagate: yes

  tourney:
    level: INFO
    handlers: [ console, tourney_file_handler ]
    propagate: no