version: 1

formatters:
  standard:
    datefmt: '%Y-%m-%d %H:%M:%S'
    format: '%(asctime)s %(name).20s %(levelname)-5s %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    formatter: standard
    stream: ext://sys.stdout

  error_console:
    class: logging.StreamHandler
    formatter: standard
    stream: ext://sys.stderr

  agents_file_handler:
    class: logging.FileHandler
    formatter: standard
    filename: logs/agents.info.log
    encoding: utf8

  agents_file_warning_handler:
    class: logging.FileHandler
    formatter: standard
    filename: logs/agents.warn.log
    encoding: utf8

  web_file_handler:
    class: logging.FileHandler
    formatter: standard
    filename: logs/web.log
    encoding: utf8

  web_access_handler:
    class: logging.FileHandler
    formatter: standard
    filename: logs/web.access.log
    encoding: utf8

  tourney_file_handler:
    class: logging.FileHandler
    formatter: standard
    filename: logs/tourney.all.log
    encoding: utf8

loggers:
  core:
    propagate: false
    level: INFO
    handlers:
      - console

  agents:
    propagate: false
    level: INFO
    handlers:
      - console
      - agents_file_handler

  agents.ml:
    propagate: false
    level: WARNING
    handlers:
      - agents_file_handler
      - error_console

  agents.adversarial:
    propagate: false
    level: WARNING
    handlers:
      - agents_file_handler
      - error_console

  agents.intereactive:
    propagate: false
    level: INFO
    handlers:
      - console
      - agents_file_handler

  web:
    level: INFO
    handlers:
      - console
      - web_file_handler

  werkzeug:
    propagate: false
    level: INFO
    handlers:
      - console
      - web_access_handler

  tourney:
    propagate: false
    level: INFO
    handlers:
      - console
      - tourney_file_handler
