terrain:

  OPEN_GROUND:
    name: 'Open Ground'
    protection: 0
    move_cost:
      infantry: 1.0
      vehicle: 1.0
    block_los: false
    color: '#92C060'

  ROAD:
    name: 'Road'
    protection: 0
    move_cost:
      infantry: 0.75
      vehicle: 0.75
    block_los: false
    color: '#E3854D'

  TREE:
    name: 'Isolated tree cover'
    protection: 2
    move_cost:
      infantry: 1.0
      vehicle: 1.0
    block_los: true
    color: '#457313'

  FOREST:
    name: 'Forest'
    protection: 4
    move_cost:
      infantry: 1.0
      vehicle: 1000.0
    block_los: true
    color: '#00410B'

  WOODEN_BUILDING:
    name: 'Wooden building'
    protection: 6
    move_cost:
      infantry: 1.0
      vehicle: 1.0
    block_los: true
    color: '#A76B11'

  CONCRETE_BUILDING:
    name: 'Concrete building'
    protection: 8
    move_cost:
      infantry: 1.0
      vehicle: 6.0
    block_los: true
    color: '#454545'
