terrain:

  OPEN_GROUND:
    name: 'Open Ground'
    protection: 0
    move_cost:
      infantry: 1.0
      vehicle: 1.0
    block_los: false

  ROAD:
    name: 'Road'
    protection: 0
    move_cost:
      infantry: 0.75
      vehicle: 0.75
    block_los: false

  TREE:
    name: 'Isolated tree cover'
    protection: 2
    move_cost:
      infantry: 1.0
      vehicle: 1.0
    block_los: true

  FOREST:
    name: 'Forest'
    protection: 4
    move_cost:
      infantry: 1.0
      vehicle: 1000.0
    block_los: true

  WOODEN_BUILDING:
    name: 'Wooden building'
    protection: 6
    move_cost:
      infantry: 1.0
      vehicle: 1.0
    block_los: true

  CONCRETE_BUILDING:
    name: 'Concrete building'
    protection: 8
    move_cost:
      infantry: 1.0
      vehicle: 6.0
    block_los: true
