figure:

  APC:
    type: vehicle

    move: 7
    load: 1
    hp: 1

    defense:
      antitank: 0

    weapons:
      MachineGun: inf
      SmokeGrenade: 2

    can_transport: true
    transport_capacity: 2
