figure:

  # Armoured Personnel Carrier
  APC:
    type: vehicle

    move: 7
    load: 1
    hp: 1

    defense:
      basic: 5
      smoke: 18
      antitank: 0

    weapons:
      MachineGun: inf
      SmokeGrenade: 2

    can_transport: true
    transport_capacity: 2
