figure:

  Auto:
    type: vehicle

    move: 4
    load: 1
    hp: 1

    defense:
      basic: 5
      smoke: 18

    weapons:
      MachineGun: inf
      SmokeGrenade: 2

    # special rules:
    # - controlled by an infantry unit
    # - contact with a unit, reload it

    # bonus:
    # - +2INT if LOS on control infantry
    # - +2INT to figures near 2 hex
    # - +1DUR (durability?)
