scenario:

  TestBench:
    map: battleground16x16

    red:
      figures:
        - rInf1:
            type: Infantry
            position: [ 3, 1 ]
        - rInf2:
            type: Infantry
            position: [ 7, 2 ]
        - rInf3:
            type: Infantry
            position: [ 6, 2 ]
        - rInf4:
            type: Infantry
            position: [ 1, 4 ]
        - rTank1:
            type: Tank
            position: [ 2, 3 ]
        - rTank2:
            type: Tank
            position: [ 2, 1 ]
      objectives:
        reach_point: [ [ 8, 8 ] ]
        eliminate_opponent:

    blue:
      figures:
        - bInf1:
            type: Infantry
            position: [ 14, 14 ]
        - bInf2:
            type: Infantry
            position: [ 13, 10 ]
            status: HIDDEN
        - bTank1:
            type: Tank
            position: [ 9, 13 ]
            status: HIDDEN

      objectives:
        defend_point: [ [ 8, 8 ] ]
        eliminate_opponent:
        max_turn: 12
