scenario:

  Test1v1:
    map: battleground16x16

    red:
      figures:
        - Tank1:
            type: Tank
            position: [ 2, 3 ]

      objectives:
        reach_point: [ [ 8, 8 ] ]
        eliminate_opponent:

    blue:
      figures:
        - Tank2:
            type: Tank
            position: [ 12, 12 ]

      objectives:
        defend_point: [ [ 8, 8 ] ]
        eliminate_opponent:
        max_turn: 12
