scenario:

  Test1v1:
    map: battleground16x16

    figures:
      red:
        - Tank:
            name: Tank1
            position: [ 2, 3 ]

      blue:
        - Tank:
            name: Tank2
            position: [ 12, 12 ]

    objectives:
      red:
        reach_point: [ [ 8, 8 ] ]
        eliminate_opponent:
      blue:
        defend_point: [ [ 8, 8 ] ]
        eliminate_opponent:
        max_turn: 12
